FROM oven/bun:1 AS build

ARG DATABASE_URL

ENV DATABASE_URL=$DATABASE_URL
ENV NODE_ENV=production

WORKDIR /app

COPY . .

RUN bun install

RUN echo "DATABASE_URL=${DATABASE_URL}" > ./apps/server/.env

RUN bunx turbo db:generate

RUN bun build \
    --compile \
    --minify-whitespace \
    --minify-syntax \
    --target bun \
    --outfile cron \
    ./apps/server/src/scripts/cron.ts

FROM gcr.io/distroless/cc-debian12 AS production

WORKDIR /app

COPY --from=build /app/cron /app/cron
COPY --from=build /app/packages/db/prisma /app/packages/db/prisma

CMD ["./cron", "checkin"]
