FROM oven/bun:1 AS production

ARG DATABASE_URL

ENV DATABASE_URL=$DATABASE_URL
ENV NODE_ENV=production

WORKDIR /app

COPY . .

RUN bun install

RUN echo "DATABASE_URL=${DATABASE_URL}" > ./apps/server/.env

RUN bunx turbo db:generate

CMD ["bun", "run", "cron:checkin"]
